# Generated by Django 3.0.1 on 2019-12-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mysite", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="sidebaritems",
            name="display",
            field=models.BooleanField(default=True),
        )
    ]
