# Generated by Django 3.0.1 on 2020-01-01 07:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191227_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
