# Generated by Django 3.0.1 on 2020-01-09 08:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200101_0709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='MultiPageContent',
        ),
        migrations.CreateModel(
            name='OnePageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('side_bar_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.SideBarItems')),
            ],
        ),
    ]
