# Generated by Django 3.0.1 on 2020-01-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200109_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipagecontent',
            old_name='side_bar_item',
            new_name='side_bar_item_id',
        ),
        migrations.RenameField(
            model_name='onepagecontent',
            old_name='side_bar_item',
            new_name='side_bar_item_id',
        ),
    ]
